# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-02 13:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0003_auto_20160102_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='body',
            field=models.TextField(blank=True, max_length=4000),
        ),
    ]
