# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-02 13:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0004_auto_20160102_1303'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ('title',),
            },
        ),
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ('pub_date',)},
        ),
        migrations.AddField(
            model_name='tag',
            name='notes',
            field=models.ManyToManyField(to='blog_app.Note'),
        ),
    ]
