# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-02 13:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0006_auto_20160102_1330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='notes',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
