# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-03 14:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0011_auto_20160102_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='body_html',
            field=models.TextField(blank=True, max_length=4000),
        ),
    ]
