# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-04 08:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0012_note_body_html'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='image',
            field=models.ImageField(blank=True, upload_to=b''),
        ),
        migrations.AlterField(
            model_name='note',
            name='body_html',
            field=models.TextField(blank=True, editable=False, max_length=4000),
        ),
    ]
