# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-04 12:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0013_auto_20160104_0834'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='%Y/%m/%d/')),
            ],
        ),
        migrations.RemoveField(
            model_name='note',
            name='image',
        ),
        migrations.AddField(
            model_name='image',
            name='note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog_app.Note'),
        ),
    ]
