# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-04 12:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0015_auto_20160104_1223'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttachedFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='%Y/%m/%d/')),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='blog_app.Note')),
            ],
        ),
        migrations.RemoveField(
            model_name='image',
            name='note',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
