# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-04 12:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0016_auto_20160104_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachedfile',
            name='note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attaches', to='blog_app.Note'),
        ),
    ]
